Group by in Pandas

In [2]:
import pandas as pd
import numpy as np
data ={
    "Name": ["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
    "Age": [22,23,None,22,25,24,26],
    "Marks": [85,None, 88,90,56,72,None],
    "Subject": ["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
}
df = pd.DataFrame(data)
print(df)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5      None  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

In [7]:
#group by subject and calculate mean mark
df.groupby("Subject")["Marks"].mean()

Subject
Chemistry    90.000000
Math         76.333333
Physics      72.000000
Name: Marks, dtype: float64

In [8]:
df.groupby("Subject")["Name"].count()

Subject
Chemistry    2
Math         3
Physics      1
Name: Name, dtype: int64

In [9]:
#Multiple Aggregations
df.groupby('Subject')['Marks'].agg(['mean', 'min', 'max'])

                mean   min   max
Subject
Chemistry  90.000000  90.0  90.0
Math       76.333333  56.0  88.0
Physics    72.000000  72.0  72.0

In [11]:
df.groupby('Subject')['Marks'].agg(['mean', 'min', 'max','count'])

                mean   min   max  count
Subject
Chemistry  90.000000  90.0  90.0      1
Math       76.333333  56.0  88.0      3
Physics    72.000000  72.0  72.0      1

In [12]:
#Group by multiple columns
df.groupby(['Subject','Age'])['Marks'].mean()

Subject    Age
Chemistry  22.0    90.0
           26.0     NaN
Math       22.0    85.0
           25.0    56.0
Physics    23.0     NaN
           24.0    72.0
Name: Marks, dtype: float64